name: Moderation
version: '${project.version}'
main: me.lagggpixel.moderation.Main
api-version: 1.19
authors: [ Lagggpixel ]
depend:
  - AdvancedVanish
commands:
  mod:
    permission: staff.mod
  freeze:
    permission: staff.freeze

permissions:
  staff.mod:
    description: Allows usage of /mod command
    default: op
  staff.freeze:
    description: Allows usage of /freeze command
    default: op

  staff.unfreezable:
    description: Makes the player un-freeze-able
    default: op
  staff.notify:
    description: Staff member is notified when a frozen player logs out